### ISSUE TITLE
Can't use retis without installed kernel config file

### ISSUE THREAD

**Issue by igsilya** [retis-org/retis#445] opened 2024-11-08 21:41 UTC
When I build my own kernels from sources, the config file is normally not installed, and retis fails to run.  At first, it says that some checks won't be performed, but then just fails entirely:

```
retis collect
WARN  Could not parse kernel configuration from known paths: some checks won't be performed
Collector(s) started: ct, skb, skb-tracking, skb-drop
Error: Could not query the kernel configuration
```

**Comment by atenart** [comment] 2024-11-14 09:47
Thanks for the report! The kernel config should be optional and I think the above issue was only introduced in #434. The `main` branch should work just fine.

(The issue is how #434 is using `inspector!().kernel.get_config_option`).

I'll fix this in the mentioned PR. Closing this, feel free to reopen if needed.

**Closed by atenart** 2024-11-14 09:47 UTC

**Comment by igsilya** [comment] 2024-11-14 11:09
> Thanks for the report! The kernel config should be optional and I think the above issue was only introduced in #434. The `main` branch should work just fine.

Ah, sorry.  I did look through the PR before opening the issue, but missed that anyway. :)
